-- begin SAMPLE_CUSTOMER
alter table SAMPLE_CUSTOMER add constraint FK_SAMPLE_CUSTOMER_DETAILS foreign key (DETAILS_ID) references SAMPLE_CUSTOMER_DETAILS(ID)^
create index IDX_SAMPLE_CUSTOMER_DETAILS on SAMPLE_CUSTOMER (DETAILS_ID)^
-- end SAMPLE_CUSTOMER
